export const homeFallback = {
  hero: {
    heading: 'Room to think.',
    body: 'Three principal floors, up to 9,762 m², in a building made for daylight. Nackagatan 4 is close to central Stockholm, without sharing its pace.',
    ctaLabel: 'See the available space',
  },
  building: {
    kicker: 'The building',
    heading: 'A 1917 mill with nearly five metres overhead.',
    body: 'Barnängshuset began as a cotton-spinning mill. The reason for its scale was practical: large working floors, ceilings approaching five metres and windows that carried daylight deep into the building. Refurbished between 2019 and 2023, those conditions now frame up to 9,762 m² of office space.',
  },
  volume: {
    kicker: 'Light and volume',
    heading: 'Daylight, all the way through.',
    body: 'High ceilings and tall factory windows bring daylight deep into each principal floor.',
    featureStatements: [
      { _key: 'ceiling', heading: '4.9-metre ceiling height', body: 'Not a specification – a condition. The distance between you and the ceiling when you actually need to think.' },
      { _key: 'windows', heading: 'Windows from floor to ceiling', body: 'Not an amenity – a legacy. Built to bring daylight deep into the building long before anyone talked about workplace wellbeing.' },
      { _key: 'breeam', heading: 'BREEAM In-Use: Excellent', body: 'The kind of certification that means the building takes the same care of its environmental commitments as it does of the people working inside it.' },
      { _key: 'charging', heading: 'EV charging in the garage', body: "Because the decision to drive electric shouldn't depend on where you park." },
      { _key: 'floor-plan', heading: 'The floor plan', body: 'Not a fixed layout – a starting condition. The building offers roughly 10,000 sq m across three floors designed before open-plan became a trend. Configure it or leave it open.' },
      { _key: 'accessibility', heading: 'Adapted for everyone', body: 'Not a feature added later — a condition built in. The building meets full accessibility standards, so the question of who can work here has a straightforward answer.' },
      { _key: 'energy', heading: 'District heating, solar panels, green electricity', body: "Three systems working quietly in the background so the building's environmental commitments don't rely on the people inside remembering to make good choices." },
      { _key: 'transport', heading: 'Close to public transport', body: "Not a consolation — a genuine advantage. Södermalm's connections make sustainable commuting the obvious choice." },
    ],
    specifications: [
      { _key: 'project', label: 'Project', value: 'Barnängshuset (Kv Barnängen)' },
      { _key: 'address', label: 'Address', value: 'Nackagatan 4, Stockholm' },
      { _key: 'premises', label: 'Types of premises', value: 'Office' },
      { _key: 'construction', label: 'Year of construction', value: '1917' },
      { _key: 'renovation', label: 'Year of renovation', value: 'Refurbished between 2019–2023' },
      { _key: 'total-area', label: 'Total area', value: '12,306 sq m (office, health care and storage)' },
      { _key: 'floors', label: 'Number of floors', value: '5 floors, including one level of underground parking' },
      { _key: 'available-area', label: 'Available area', value: '9,762 sq m' },
      { _key: 'single-tenant', label: 'Single tenant / whole single solution', value: 'Yes' },
      { _key: 'move-in', label: 'Planned move-in date', value: 'According to agreement' },
      { _key: 'certification', label: 'Environmental certification', value: 'BREEAM In-Use: Excellent' },
      { _key: 'electricity', label: 'Electricity', value: 'Own subscription' },
      { _key: 'waste', label: 'Waste', value: 'Available in the building' },
      { _key: 'agreement', label: 'Agreement type', value: 'First-hand agreement' },
      { _key: 'term', label: 'Agreement length', value: 'Upon agreement' },
      { _key: 'security', label: 'Financial security', value: 'Upon agreement' },
      { _key: 'ventilation', label: 'Ventilation capacity', value: '1 person / 8 sq m' },
      { _key: 'internet', label: 'Internet connection', value: 'Fiber' },
      { _key: 'parking', label: 'Car parking', value: '69 parking spaces (including 2 MC spaces)' },
      { _key: 'bicycles', label: 'Bicycle parking', value: '30 cycle stands' },
      { _key: 'ev', label: 'Electricity charging stations', value: '17 stations' },
      { _key: 'loading', label: 'Loading capabilities', value: 'Loading bay and goods lift' },
      { _key: 'storage', label: 'Storage', value: 'Available in the building' },
      { _key: 'changing', label: 'Changing room', value: 'Located on garage plan and refurbished in 2023' },
      { _key: 'epc', label: 'EPC', value: 'Energy class C, 116 kWh/sq m per year' },
    ],
  },
  gallery: {
    kicker: 'A closer look',
    heading: 'From Nackagatan to the floorplate.',
    body: 'The gallery follows the route through the building: façade, stair, working floor and material detail.',
    items: [
      { _key: 'arrival', caption: 'Arrival · Nackagatan façade', layout: 'wide' },
      { _key: 'vertical', caption: 'Vertical core · stair and light', layout: 'portrait' },
      { _key: 'working', caption: 'Working volume · windows and floorplate', layout: 'wide' },
      { _key: 'material', caption: 'Material detail · brick and stone', layout: 'compact' },
    ],
  },
  opportunity: {
    kicker: 'The opportunity',
    heading: 'Nearly 10,000 m² on Södermalm.',
    body: 'The available space extends across three principal office floors. It is presented as one coherent workplace.',
    ctaLabel: 'Discuss the space',
    facts: [
      { _key: 'area', label: 'Available area', value: 'Up to 9,762 m²' },
      { _key: 'floors', label: 'Office floors', value: 'Three principal floors' },
      { _key: 'move-in', label: 'Move-in', value: 'By agreement' },
    ],
  },
  materials: {
    kicker: 'Material character',
    heading: 'Brick, steel, oak and stone.',
    body: 'Original brick and structural steel sit alongside oak, terrazzo, stone and dark metalwork introduced during refurbishment.',
  },
  place: {
    kicker: 'The address',
    heading: 'Södermalm, at a quieter edge.',
    body: 'Nackagatan 4 is close to Vitabergsparken, local restaurants and the water.',
    nearby: [
      { _key: 'vita', name: 'Vitabergsparken', detail: 'A short walk' },
      { _key: 'slussen', name: 'Slussen', detail: '9 min by bus' },
      { _key: 'skanstull', name: 'Skanstull', detail: '2 min by metro' },
      { _key: 'kanal', name: 'Hammarby kanal', detail: 'Future metro, 2030' },
    ],
  },
  viewing: {
    kicker: 'Arrange a viewing',
    heading: 'See the floors in person.',
    body: 'A viewing covers the available floors, daylight conditions and the practical requirements of your organisation.',
    ctaLabel: 'Arrange a viewing',
  },
}

export const contactFallback = {
  name: 'Nina de Besche',
  role: 'Managing Partner',
  email: 'nina.debesche@avantipartners.se',
  phone: '+46 733 49 87 46',
}
