export const homeFallback = {
  hero: {
    heading: 'Room to think.',
    body: 'Three principal floors, up to 9,762 m², in a building made for daylight. Nackagatan 4 is close to central Stockholm, without sharing its pace.',
    ctaLabel: 'See the available space',
  },
  building: {
    kicker: 'The building',
    heading: 'A 1917 mill with nearly five metres overhead.',
    body: 'Barnängshuset began as a cotton-spinning mill. The reason for its scale was practical: large working floors, ceilings approaching five metres and windows that carried daylight deep into the building. Refurbished between 2019 and 2023, those conditions now frame up to 9,762 m² of office space.',
  },
  volume: {
    kicker: 'Light and volume',
    heading: 'Daylight, all the way through.',
    body: 'High ceilings and tall factory windows bring daylight deep into each principal floor.',
    featureStatements: [
      { _key: 'ceiling', heading: '4.9-metre ceiling height', body: 'Not a specification – a condition. The distance between you and the ceiling when you actually need to think.' },
      { _key: 'windows', heading: 'Windows from floor to ceiling', body: 'Not an amenity – a legacy. Built to bring daylight deep into the building long before anyone talked about workplace wellbeing.' },
      { _key: 'breeam', heading: 'BREEAM In-Use: Excellent', body: 'The kind of certification that means the building takes the same care of its environmental commitments as it does of the people working inside it.' },
      { _key: 'charging', heading: 'EV charging in the garage', body: "Because the decision to drive electric shouldn't depend on where you park." },
      { _key: 'floor-plan', heading: 'The floor plan', body: 'Not a fixed layout – a starting condition. The building offers roughly 10,000 sq m across three floors designed before open-plan became a trend. Configure it or leave it open.' },
      { _key: 'accessibility', heading: 'Adapted for everyone', body: 'Not a feature added later — a condition built in. The building meets full accessibility standards, so the question of who can work here has a straightforward answer.' },
      { _key: 'energy', heading: 'District heating, solar panels, green electricity', body: "Three systems working quietly in the background so the building's environmental commitments don't rely on the people inside remembering to make good choices." },
      { _key: 'transport', heading: 'Close to public transport', body: "Not a consolation — a genuine advantage. Södermalm's connections make sustainable commuting the obvious choice." },
    ],
  },
  specifications: {
    kicker: 'Light and volume',
    heading: 'Daylight, all the way through.',
    body: 'High ceilings and tall factory windows bring daylight deep into each principal floor.',
    specificationGroups: [
      { _key: 'building', title: 'Building', facts: [
        { _key: 'project', label: 'Project', value: 'Barnängshuset (Kv Barnängen)' },
        { _key: 'address', label: 'Address', value: 'Nackagatan 4, Stockholm' },
        { _key: 'premises', label: 'Premises', value: 'Office' },
        { _key: 'construction', label: 'Construction', value: '1917' },
        { _key: 'renovation', label: 'Renovation', value: '2019–2023' },
        { _key: 'total-area', label: 'Total area', value: '12,306 sq m' },
        { _key: 'floors', label: 'Floors', value: '5, including underground parking' },
      ] },
      { _key: 'availability', title: 'Availability', facts: [
        { _key: 'available-area', label: 'Available area', value: '9,762 sq m' },
        { _key: 'single-tenant', label: 'Whole solution', value: 'Single tenant' },
        { _key: 'move-in', label: 'Move-in', value: 'According to agreement' },
      ] },
      { _key: 'agreement', title: 'Agreement', facts: [
        { _key: 'agreement-type', label: 'Type', value: 'First-hand agreement' },
        { _key: 'term', label: 'Length', value: 'Upon agreement' },
        { _key: 'security', label: 'Financial security', value: 'Upon agreement' },
      ] },
      { _key: 'performance', title: 'Performance', facts: [
        { _key: 'certification', label: 'Certification', value: 'BREEAM In-Use: Excellent' },
        { _key: 'electricity', label: 'Electricity', value: 'Own subscription' },
        { _key: 'waste', label: 'Waste', value: 'Available in the building' },
        { _key: 'ventilation', label: 'Ventilation', value: '1 person / 8 sq m' },
        { _key: 'internet', label: 'Internet', value: 'Fiber' },
        { _key: 'epc', label: 'EPC', value: 'Energy class C, 116 kWh/sq m per year' },
      ] },
      { _key: 'access', title: 'Access', facts: [
        { _key: 'parking', label: 'Car parking', value: '69 spaces, including 2 MC spaces' },
        { _key: 'bicycles', label: 'Bicycle parking', value: '30 cycle stands' },
        { _key: 'ev', label: 'EV charging', value: '17 stations' },
        { _key: 'loading', label: 'Loading', value: 'Loading bay and goods lift' },
      ] },
      { _key: 'facilities', title: 'Facilities', facts: [
        { _key: 'storage', label: 'Storage', value: 'Available in the building' },
        { _key: 'changing', label: 'Changing room', value: 'Garage level, refurbished in 2023' },
      ] },
    ],
  },
  gallery: {
    kicker: 'A closer look',
    heading: 'From Nackagatan to the floorplate.',
    body: 'The gallery follows the route through the building: façade, stair, working floor and material detail.',
    items: [
      { _key: 'arrival', caption: 'Arrival · Nackagatan façade', layout: 'wide' },
      { _key: 'vertical', caption: 'Vertical core · stair and light', layout: 'portrait' },
      { _key: 'working', caption: 'Working volume · windows and floorplate', layout: 'wide' },
      { _key: 'material', caption: 'Material detail · brick and stone', layout: 'compact' },
    ],
  },
  mosaicGallery: {
    kicker: '',
    heading: '',
    items: [
      { _key: 'mosaic-1', caption: 'The principal working floor', size: 'portrait', side: 'left' },
      { _key: 'mosaic-2', caption: 'Original windows and structure', size: 'compact', side: 'right' },
      { _key: 'mosaic-3', caption: 'Material detail', size: 'compact', side: 'left' },
      { _key: 'mosaic-4', caption: 'The building from Nackagatan', size: 'wide', side: 'right' },
      { _key: 'mosaic-5', caption: 'Stair and circulation', size: 'portrait', side: 'left' },
      { _key: 'mosaic-6', caption: 'Space for a shared workplace', size: 'wide', side: 'right' },
    ],
  },
  opportunity: {
    kicker: 'The opportunity',
    heading: 'Nearly 10,000 m² on Södermalm.',
    body: 'The available space extends across three principal office floors. It is presented as one coherent workplace.',
    ctaLabel: 'Discuss the space',
    facts: [
      { _key: 'area', label: 'Available area', value: 'Up to 9,762 m²' },
      { _key: 'floors', label: 'Office floors', value: 'Three principal floors' },
      { _key: 'move-in', label: 'Move-in', value: 'By agreement' },
    ],
  },
  materials: {
    kicker: 'Material character',
    heading: 'Brick, steel, oak and stone.',
    body: 'Original brick and structural steel sit alongside oak, terrazzo, stone and dark metalwork introduced during refurbishment.',
  },
  place: {
    kicker: 'The address',
    heading: 'Södermalm, at a quieter edge.',
    body: 'Nackagatan 4 is close to Vitabergsparken, local restaurants and the water.',
    nearby: [
      { _key: 'vita', name: 'Vitabergsparken', detail: 'A short walk' },
      { _key: 'slussen', name: 'Slussen', detail: '9 min by bus' },
      { _key: 'skanstull', name: 'Skanstull', detail: '2 min by metro' },
      { _key: 'kanal', name: 'Hammarby kanal', detail: 'Future metro, 2030' },
    ],
  },
  areaMap: {
    kicker: 'In the area',
    heading: 'Close at hand.',
    supportingLine: 'Every point below is a real walk from Nackagatan 4 — the minutes are honest.',
    // No mapImage — upload one in Sanity (Area map → Map image), then place
    // pins via each poi's mapX/mapY. buildingX/Y below are illustrative.
    buildingX: 68,
    buildingY: 38,
    pois: [
      { _id: 'poi-balue', name: 'Balue', description: 'Coffee bar', category: 'coffee', walkingMinutes: 9, mapX: 38, mapY: 22, lat: 59.3168, lng: 18.0819, sortOrder: 1 },
      { _id: 'poi-sairu-sushi', name: 'Sairu Sushi', description: 'Sushi', category: 'lunch', walkingMinutes: 10, mapX: 42, mapY: 18, lat: 59.3175, lng: 18.0831, sortOrder: 2 },
      { _id: 'poi-stella', name: 'Stella Pizza Restaurant', description: 'Pizza', category: 'lunch', walkingMinutes: 4, mapX: 60, mapY: 55, lat: 59.3138, lng: 18.0742, sortOrder: 3, showRoute: true },
      { _id: 'poi-lulu', name: 'Lulu, Poke and Sushi Bar', description: 'Poke and sushi', category: 'lunch', walkingMinutes: 5, mapX: 63, mapY: 50, lat: 59.3142, lng: 18.0765, sortOrder: 4 },
      { _id: 'poi-taza', name: 'Taza Artisan Café', description: 'Coffee', category: 'coffee', walkingMinutes: 5, mapX: 58, mapY: 58, lat: 59.3130, lng: 18.0735, sortOrder: 5 },
      { _id: 'poi-kajsas-parken', name: 'Kajsas i Parken', description: 'Café in the park', category: 'lunch', walkingMinutes: 3, mapX: 62, mapY: 46, lat: 59.3129, lng: 18.0748, sortOrder: 6, showRoute: true },
      { _id: 'poi-kajsas-kajen', name: 'Kajsas på Kajen', description: 'Ice cream café', category: 'coffee', walkingMinutes: 6, mapX: 66, mapY: 60, lat: 59.3118, lng: 18.0762, sortOrder: 7 },
      { _id: 'poi-mormors', name: 'Mormors Restaurant and Dumplings', description: 'Dumplings', category: 'lunch', walkingMinutes: 8, mapX: 50, mapY: 28, lat: 59.3161, lng: 18.0798, sortOrder: 8 },
      { _id: 'poi-bleck', name: 'Restaurant Bleck', description: 'Restaurant', category: 'wine', walkingMinutes: 7, mapX: 48, mapY: 42, lat: 59.3151, lng: 18.0698, sortOrder: 9 },
      { _id: 'poi-restaurant-nytorget', name: 'Restaurant Nytorget', description: 'Restaurant', category: 'lunch', walkingMinutes: 9, mapX: 40, mapY: 20, lat: 59.3170, lng: 18.0822, sortOrder: 10 },
      { _id: 'poi-urban-deli', name: 'Urban Deli', description: 'Grocer and restaurant', category: 'lunch', walkingMinutes: 10, mapX: 43, mapY: 17, lat: 59.3173, lng: 18.0827, sortOrder: 11 },
      { _id: 'poi-bar-agrikultur', name: 'Bar Agrikultur', description: 'Wine bar', category: 'wine', walkingMinutes: 11, mapX: 46, mapY: 14, lat: 59.3178, lng: 18.0836, sortOrder: 12 },
      { _id: 'poi-meatballs', name: 'Meatballs for the People', description: 'Restaurant', category: 'lunch', walkingMinutes: 10, mapX: 41, mapY: 24, lat: 59.3176, lng: 18.0812, sortOrder: 13 },
      { _id: 'poi-cafe-nizza', name: 'Cafe Nizza', description: 'Coffee', category: 'coffee', walkingMinutes: 6, mapX: 55, mapY: 62, lat: 59.3133, lng: 18.0700, sortOrder: 14 },
      { _id: 'poi-rot-shop', name: 'Rot Shop & Kitchen', description: 'Restaurant', category: 'lunch', walkingMinutes: 8, mapX: 52, mapY: 65, lat: 59.3140, lng: 18.0680, sortOrder: 15 },
      { _id: 'poi-svedjan', name: 'Svedjan', description: 'Bakery', category: 'coffee', walkingMinutes: 8, mapX: 54, mapY: 63, lat: 59.3145, lng: 18.0685, sortOrder: 16 },
      { _id: 'poi-orion', name: 'Orion Theathre', description: 'Theatre', category: 'culture', walkingMinutes: 12, mapX: 35, mapY: 68, lat: 59.3122, lng: 18.0655, sortOrder: 17 },
      { _id: 'poi-stc-gym', name: 'STC Gym', description: 'Gym', category: 'gym', walkingMinutes: 5, mapX: 50, mapY: 48, lat: 59.3140, lng: 18.0725, sortOrder: 18 },
      { _id: 'poi-friskis', name: 'Friskis & Svettis', description: 'Gym', category: 'gym', walkingMinutes: 14, mapX: 28, mapY: 75, lat: 59.3105, lng: 18.0680, sortOrder: 19 },
      { _id: 'poi-thaiboat', name: 'Thaiboat', description: 'Restaurant', category: 'lunch', walkingMinutes: 22, mapX: 82, mapY: 82, lat: 59.3070, lng: 18.0980, sortOrder: 20 },
      { _id: 'poi-carnegie', name: 'Nya Carnegiebryggeriet', description: 'Brewery', category: 'wine', walkingMinutes: 25, mapX: 90, mapY: 88, lat: 59.3048, lng: 18.1050, sortOrder: 21 },
      { _id: 'poi-sjostadens', name: 'Sjöstadens Marina Restaurant', description: 'Restaurant', category: 'lunch', walkingMinutes: 26, mapX: 88, mapY: 90, lat: 59.3040, lng: 18.1070, sortOrder: 22 },
      { _id: 'poi-indian-street', name: 'Indian Street Food & Co', description: 'Restaurant', category: 'lunch', walkingMinutes: 23, mapX: 85, mapY: 86, lat: 59.3055, lng: 18.1010, sortOrder: 23 },
    ],
  },
  viewing: {
    kicker: 'Arrange a viewing',
    heading: 'See the floors in person.',
    body: 'A viewing covers the available floors, daylight conditions and the practical requirements of your organisation.',
    ctaLabel: 'Arrange a viewing',
  },
}

export const contactFallback = {
  name: 'Nina de Besche',
  role: 'Managing Partner',
  email: 'nina.debesche@avantipartners.se',
  phone: '+46 733 49 87 46',
}
